<!DOCTYPE html>
<html lang="en">
<head>
	<title>LOGIN</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="../css/min.css">
</head>
<body>
	<!-- log in form-->
     <form action="login-checkup.php" method="post"  >
    <!--php notify-->
     	<img src="../assets/icons/logo.png" class="logo-sgnup" alt="logo">
     	<!--Text-Box -->
		 <section class="input-btn-all">
         <input type="text" name="firstname" placeholder="Firstname...">
         <input type="text" name="surname" placeholder="Surname...">
         <input type="address" name="address" placeholder="home address...">
     	<input type="text" name="username" placeholder="username...">
     	<input type="password" name="pwd"  placeholder="Password">
		<button type="submit">Signup</button><br>
		<p class="fgt-pss-wrd">
			<span><a href="">Q&A</a></span> | 
			I already have an <a href="../files/login.html">account</a> | 
			<span><a href="#">Help</a></span>
		</p>
		</section>
     </form>

</body>

</html>